name: Push helm chart

on:
  workflow_dispatch:
    inputs:
      chart:
        description: 'chart to push on this public repo'
        required: true
        type: string

jobs:
  push-chart:
    runs-on: self-hosted

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.chart }}"
